### PR TITLE
Release versions

### PR DESCRIPTION
**Pull request by timfallmk**
See https://github.com/vapor-ware/ksync/compare/release-versions?expand=1#diff-c860d8d6e153d9a32df0a3ced416dfdeR9 for details.

https://circleci.com/gh/organizations/vapor-ware/settings#contexts

### CODE REVIEW

**Comment by timfallmk** [comment]
Fixed:
```shell
ksync version --log-level warning
ksync:
	Version:    corrupted-version
	Go Version: go1.9.2
	Git Commit: 0bfd9c1
	Git Tag:    
	Built:      Thu Dec 14 21:05:48 +0000 2017
	OS/Arch:    darwin/amd64
radar:
	Version:    Release
	Go Version: go1.9.2
	Git Commit: 7dd4fa0
	Git Tag:    
	Built:      Thu Dec 14 23:33:33 +0000 2017
	Healthy:    true
```

`ksync` binary shows old behavior, `radar` shows new behavior. `Git Tag` is no populated because this release is not at a tag.

**Comment by timfallmk** [comment]
@pyronicide I also suggest we remove the `v` from the tags for easier future parsing.

**Comment by pyronicide** [comment]
@timfallmk I'd assumed that `Version: 1.0.0` would be the value, not `Version: Release`?

**Comment by timfallmk** [comment]
It could be, but it would be a bit redundant given the tags are shown

via Newton Mail [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=9.8.139&pv=11.2&source=email_footer_2]
On Fri, Dec 15, 2017 at 6:42, Thomas Rampelberg <notifications@github.com> wrote:
@timfallmk [https://github.com/timfallmk] I'd assumed that Version: 1.0.0 would be the value, not Version: Release ?

**Pull request merged**
